# Generated by Django 3.0.5 on 2020-04-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopboard',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('pass_field', models.CharField(db_column='pass', max_length=20)),
                ('mail', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('cont', models.TextField(blank=True, null=True)),
                ('bip', models.CharField(blank=True, max_length=20, null=True)),
                ('bdate', models.CharField(blank=True, max_length=50, null=True)),
                ('readcnt', models.IntegerField(blank=True, null=True)),
                ('gnum', models.IntegerField(blank=True, null=True)),
                ('onum', models.IntegerField(blank=True, null=True)),
                ('nested', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shopboard',
                'managed': False,
            },
        ),
    ]
